# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5a337e563d03098f08d962c5e0a6f684b46a56d395efbe8e6b7927a5def47be153d9c60b2c371470186b3115b96e0d327037a379590a294b150bf7e70283885

test:
  secret_key_base: 07fc836b11b2d6d1b5a77a6f20fd0190ff44e31e53fb3856cf854d18881a569caa7d48eaebbfb64d5b629a22a8d825fc97a3bafa0838151ad66d9b6b3e530232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
